# Generated by Django 5.2.3 on 2025-06-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
